### ISSUE TITLE
Lab built. needs review

### ISSUE THREAD

**Issue by dfenjves** [learn-co-curriculum/regex-lab#1]
@AnnJohn @jmburges @StevenNunez

**Comment by AnnJohn** [comment]
Assigned to @StevenNunez

**Comment by octosteve** [comment]
@dfenjves This is great! Happy to see some Regex Labs finally :-)

**Comment by AnnJohn** [comment]
@dfenjves can you delete the lab-content branch? thanks!

**Comment by dfenjves** [comment]
done

**Comment by AnnJohn** [comment]
thanks!
