### ISSUE TITLE
Need more content

### ISSUE THREAD

**Issue by joshuaneedham** [learn-co-curriculum/regex-lab#13]
I found this lab to be a bit difficult based on the information and resources provided. May want to consider including more information about things like the `* . +` operators which were mentioned in the regex basics objectives section but not mentioned in the content. Providing a couple of different examples that include `? true : false` may also be beneficial as a refresher to get us all thinking about other ways to solve.

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in issue #15. We will add this to our internal work queue. 

We're closing this issue but invite you to follow the progress and we will notify you when it is resolved.

-- Flatiron Curriculum Team
