### ISSUE TITLE
Lessons Are Not Clear Leading Up to The LAb

### ISSUE THREAD

**Issue by jmulloy** [learn-co-curriculum/regex-lab#16]
The lessons for RegEx are good. They explain what it is and the different ways to use it in ruby. However, when you get to the lab, it is very tough to use what was learned in readings to get through the lab. I utilized different resources from Google to the AAQ forum on the lab. I passed but it took a while due to not fully understanding what needed to be done within the code. Maybe add a few more lessons and a deeper explanation of the functionality of the regex and how to utilize it within ruby. 

Just a thought!

**Comment by cjbrock** [comment]
Hello,

We're always working to improve the curriculum. This is helpful feedback and we'll take it into consideration as we make future updates. Thank you for taking your time to help us make Learn a better place.

// <3 Corinna
