### ISSUE TITLE
Negative Test for valid_phone_number? Can Yield False Positive

### ISSUE THREAD

**Issue by Tokuhisa1** [learn-co-curriculum/regex-lab#18]
The negative test for the valid_phone_number? method can yield a false positive if matching on the pattern "/\D?\d{3}[\D\s]?\d{3}[\D\s]?\d{4}/". This returns "true" when the method is called on [in]valid_numbers[1] ("(718)891-13135"). Whereas, it should return "false", if the pattern is not something like "/\D?\d{3}[\D\s]?\d{3}[\D\s]?\d{4}/$".

**Comment by drakeltheryuujin** [comment]
Hi @Tokuhisa1,

Thank you for your feedback! We'll take this information into consideration in upcoming releases of this curriculum.

As always, thanks for contributing! 💙
